foodie_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
     path('', include('landing.urls')),
    path('admin/', admin.site.urls),
] 

wine/urls.py
from django.urls import path

from .views import WineHomeView, WineCreateView, WineEditView, load_regions, WineFilterListView, WineSearchView, WineDeleteView, WineAPI


urlpatterns = [
    #HOME
    path('', WineHomeView, name='wine-home'),
    #WINE
    path('add/', WineCreateView.as_view(), name='add-wine'),
    path('list/', WineFilterListView, name='wine-list'),
    path('edit/<int:pk>',WineEditView.as_view(), name='wine-edit' ),
    path('search/', WineSearchView, name='wine-search'),
    path('delete/<int:pk>', WineDeleteView.as_view(), name='delete-wine'),
    #REGION LIST
    path('ajax/load-regions/', load_regions, name='ajax_load_regions'),
    #API
    path('api/', WineAPI.as_view(), name='wine-api')
]

wine/models.py
from django.db import models

# Create your models here.
class Country(models.Model):
    country = models.CharField(max_length=20)

    def __str__(self):
        return self.country


class Region(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    region = models.CharField(max_length=40)

    def __str__(self):
        return self.region


class Wine(models.Model):
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    region = models.ForeignKey(Region, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=100)
    vintage = models.IntegerField(blank=True, null=True)
    retailer = models.CharField(max_length=100, blank=True)
    price = models.FloatField(blank=True, null=True)
    comment = models.CharField(max_length=100, blank=True)
    blend = models.CharField(max_length=100, blank=True)
    vg_rating = models.FloatField(blank=True, null=True, verbose_name="Vince's Rating")
    entry_dt = models.DateField(auto_now_add=True)
    amend_dt = models.DateField(blank=True, null=True)
    url = models.URLField(blank=True)


    #2/3 1/3 wine list and wine filter. 
  

    #pass the retailers and blend in as a drop down to avoid mispellings

    def __str__(self):
        return self.name

wine/forms.py
from django import forms
from django.forms import ModelForm
from .models import Wine, Country, Region


class AddWineForm(ModelForm):
        class Meta:
            model = Wine
            fields = ['country', 'region', 'name', 'vintage',
                        'retailer', 'price', 'comment', 'blend',
                        'vg_rating', 'url'
                    ]
            
            
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['region'].queryset = Region.objects.none()
            # self.fields['region'].queryset = Region.objects.all().order_by('region')
            # self.fields['country'].queryset = Country.objects.all().order_by('country')

            if 'country' in self.data:
                try:
                    country_id = int(self.data.get('country'))
                    self.fields['region'].queryset = Region.objects.filter(country_id=country_id).order_by('region')
                except (ValueError, TypeError):
                    pass  # invalid input from the client; ignore and fallback to empty     Region queryset
            elif self.instance.pk:
                self.fields['region'].queryset = Region.objects.filter(self.instance.country).order_by('region')
            

   
class EditWineForm(ModelForm):
        class Meta:
            model = Wine
            fields = ['country', 'region', 'name', 'vintage',
                        'retailer', 'price', 'comment', 'blend',
                        'vg_rating', 'url'
                    ]
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['region'].queryset = Region.objects.all().order_by('region')
            self.fields['country'].queryset = Country.objects.all().order_by('country')

            print(self.data)

#do the same as above to filter the region and then do as per the you tube for the filter...
class WineFilterForm(ModelForm):
    class Meta:
        model = Wine
        fields = ['country', 'region', 'vg_rating']   

    def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['region'].queryset = Region.objects.none()

            
            if 'country' in self.data:
                try:
                    print("Country in self data")
                    country_id = int(self.data.get('country'))
                    self.fields['region'].queryset = Region.objects.filter(country_id=country_id).order_by('region')
                except (ValueError, TypeError):
                    pass  # invalid input from the client; ignore and fallback to empty     Region queryset
            elif self.instance.pk:
                print("Country not in self data")
                self.fields['region'].queryset = Region.objects.filter(self.instance.country).order_by('region')          

wine/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from django.core.paginator import Paginator
from .serializers import WineSerializer
from rest_framework import generics
from .models import Wine, Region, Country
from .forms import AddWineForm, WineFilterForm, EditWineForm

# Serializer
class WineAPI(LoginRequiredMixin,generics.ListAPIView):
    queryset = Wine.objects.all()


    serializer_class = WineSerializer


def WineHomeView(request):
    return render(request, 'wine/home.html')

class WineCreateView(LoginRequiredMixin, CreateView):
    # model = Wine
    queryset= Wine.objects.order_by('country__country')
    form_class = AddWineForm
    template_name = 'wine/wine_add.html'
    success_url = reverse_lazy('wine-list')


#this is the view for the dependent dropdown list form.. Try later...
# class WineListView(LoginRequiredMixin, ListView):
#     model = Wine
#     form_class = WineFilterForm
#     context_object_name = 'wines'
#     template_name = 'wine/wine_list.html'

@login_required
def WineFilterListView(request):
    qs  = Wine.objects.all()

    country_name = request.GET.get('country')
    region_name = request.GET.get('region')
    vg_rating = request.GET.get('vg_rating')

    if region_name == None:
        if country_name != None:
            qs = Wine.objects.filter(country__country=country_name).order_by('country')
        if vg_rating != '' and vg_rating != None:
            qs = qs.filter(vg_rating__gte=vg_rating).order_by('-id')
    else:
        qs = qs.filter(region__region=region_name).order_by('-id')


    # Get country and region list and sort
    country_list = [i.country.country for i in Wine.objects.distinct('country')]
    country_list.sort()

    region_list = [i.region.region for i in Wine.objects.distinct('region')]
    region_list.sort()

    sort_qs = qs.order_by('country__country', 'region__region')

    # Pagination
    # paginator = Paginator(sort_qs, 12) 
    # page_number = request.GET.get('page')
    # page_obj = paginator.get_page((page_number))
 

    context = {
        'wines': sort_qs,  #page_obj, if we are using pagination
        'country': country_list,
        'region': region_list,
        'vg_rating': Wine.objects.order_by('vg_rating').distinct('vg_rating')
    }

    return render(request, 'wine/wine_list.html', context)

class WineEditView(LoginRequiredMixin, UpdateView):
    model = Wine
    form_class = EditWineForm
    template_name = 'wine/wine_edit.html'
    success_url = reverse_lazy('wine-list')


def WineSearchView(request):
    return render(request, 'wine/wine_search.html')


def load_regions(request):
    country_id = request.GET.get('country')
    print(country_id)
    regions = Region.objects.filter(country_id=country_id).order_by('region')

    return render(request, 'wine/region_list.html', {'regions': regions})
    

class WineDeleteView(LoginRequiredMixin, DeleteView):
    model = Wine
    template_name = 'wine/wine_delete.html'
    success_url = reverse_lazy('wine-list')

wine/templates/wine/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

        <!-- Favicon -->
   <link rel="shortcut icon" href="{% static 'wine/img/favicon.ico' %}" >
   <link rel="icon" type="image/gif" href="{% static 'wine/img/animated_favicon1.gif'%}" >

    <title>Wine</title>

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'wine/css/wine_style.css' %}"
    />
  </head>


  <body>
      <nav id="wine-nav" class="navbar navbar-expand-sm navbar-dark sticky-top bg-dark">
        <div class="container">
          <a href="{% url 'landing-home' %}" class="navbar-brand">Home</a>
          <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarContent"
          >
            <span class="navbar-toggler-icon"></span>
          </button>

          <!--make navbar highlight selected navbar link-->
          <div class="collapse navbar-collapse" id="navbarContent">
            <ul class="navbar-nav mr-auto">
                <li
                    {% if '/wine/' == request.path %}
                    class="nav-item active mr-3"
                    {% else %}
                    class="nav-item mr-3"
                    {% endif %}
                >
              <a class="nav-link" href="{% url 'wine-home' %}">Wine Home</a>
              </li>

              <li
                    {% if '/wine/list/' in request.path %}
                    class="nav-item active mr-3"
                    {% else %}
                    class="nav-item mr-3"
                    {% endif %}
                >
              <a class="nav-link" href="{% url 'wine-list' %}">Wine List</a>
              </li>

              <li
                    {% if '/wine/add/' in request.path %}
                    class="nav-item active mr-3"
                    {% else %}
                    class="nav-item mr-3"
                    {% endif %}
                >
              <a class="nav-link" href="{% url 'add-wine' %}">Add Wine</a>
              </li>

              <li
                    {% if '/wine/search/' in request.path %}
                    class="nav-item active mr-3"
                    {% else %}
                    class="nav-item mr-3"
                    {% endif %}
                >
              <a class="nav-link" href="{% url 'wine-search' %}">Wine Search</a>
              </li>
            </ul>
            <form class="form-inline">
              <a
                class="btn btn-danger navbar-right"
                href="{% url 'logout' %}"
                >Log Out</a
              >
            </form>
          </div>
      </nav>
      {% block content %} {% endblock %}


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

wine/templates/wine/home.html
{% extends 'wine/base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}
<style>
    body, html {
    background-image: url('{% static "wine/img/grapes.jpg" %}');
    background-repeat: no-repeat;
    background-position: center;
    background-size: cover;
    height: 100%;
    }
</style>


{% endblock content %}

wine/templates/wine/region_list.html
<option value="">---------</option>
{% for region in regions %}
<option value="{{ region.pk }}">{{ region.region }}</option>
{% endfor %}

wine/templates/wine/wine_add.html
{% extends 'wine/base.html' %} 
{% load crispy_forms_tags %} 
{% block content %}
<style>
  body {
    overflow: hidden;
  }
</style>


<section id="add-wine">
<div class="container" >
  <div class="row justify-content-center">
    <div class="col-6 border mb-2 add-wine-form">
      <h5 class="text-center py-2">Add Wine</h5>
      <form method="post" enctype="multipart/form-data" id="wineForm" data-regions-url="{% url 'ajax_load_regions' %}" novalidate>
        <div class="form-group">
          {% csrf_token %}
                    <div class="row">
            <div class="col-12">
              {{ form.name|as_crispy_field}}
            </div>
          </div>
          <div class="row">
            <div id="country" class="col-4">
              {{ form.country|as_crispy_field}}
            </div>
            <div class="col-4">
              {{ form.region|as_crispy_field}}
            </div>
            <div class="col-4">
              {{ form.vintage|as_crispy_field}}
            </div>
          </div>
          <div class="row">
            <div class="col-4">
              {{ form.retailer|as_crispy_field}}
            </div>
            <div class="col-4">
              {{ form.price|as_crispy_field}}
            </div>
            <div class="col-4">
              {{ form.vg_rating|as_crispy_field}}
            </div>
          </div>
          <div class="row">
            <div class="col-8">
              {{ form.comment|as_crispy_field}}
            </div>
          </div>
          <div class="row">
            <div class="col-8">
              {{ form.blend|as_crispy_field}}
            </div>
          </div>
          <div class="row">
            <div class="col-12">
              {{ form.url|as_crispy_field}}
            </div>
          </div>
        </div>
        <div class="container">
        <button type="submit" class="btn btn-primary col-3 mb-2">Submit</button>
        <a href="{% url 'wine-list' %}" class="btn btn-danger col-3 mb-2 float-right">Cancel</a>
        </div>
      </form>
    </div>
  </div>
</div>
</section>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

  <script>
    $("#id_country").change(function () {
      var url = $("#wineForm").attr("data-regions-url");  // get the url of the `load_cities` view
      var countryId = $(this).val();  // get the selected country ID from the HTML input

      

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'country': countryId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_region").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });
        
    }); 

 
  </script>


{% endblock %}

wine/templates/wine/wine_delete.html
{% extends 'wine/base.html' %}
{% block content %}

<div class="container mt-5 text-center mx-auto">
<form method="post">{% csrf_token %}
    
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <button class="btn btn-danger" type="submit">Delete</button>
     <a href="{% url 'wine-list' %}" class="btn btn-info">Cancel</a>
</form>
</div>

{% endblock %}

wine/templates/wine/wine_edit.html
{% extends 'wine/base.html' %}
{% load crispy_forms_tags %} 
{% block content %}

<section id="edit-wine">
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-6 border mb-2 edit-wine-form">
      <h5 class="text-center mt-3">Edit Wine</h5>
      <form id="wine-edit-form" method="post" enctype="multipart/form-data">
        <div class="form-group">
          {% csrf_token %} 
          <div class="row">
            <div class="col-12">
              {{ form.name|as_crispy_field}}
            </div>
          </div>
          <div class="row">
            <div class="col-4">
              {{ form.country|as_crispy_field}}
            </div>
            <div class="col-4">
              {{ form.region|as_crispy_field}}
            </div>
            <div class="col-4">
              {{ form.vintage|as_crispy_field}}
            </div>
          </div>
          <div class="row">
            <div class="col-4">
              {{ form.retailer|as_crispy_field}}
            </div>
            <div class="col-4">
              {{ form.price|as_crispy_field}}
            </div>
            <div class="col-4">
              {{ form.vg_rating|as_crispy_field}}
            </div>
          </div>
          <div class="row">
            <div class="col-8">
              {{ form.comment|as_crispy_field}}
            </div>
          </div>
          <div class="row">
            <div class="col-8">
              {{ form.blend|as_crispy_field}}
            </div>
          </div>
          <div class="row">
            <div class="col-12">
              {{ form.url|as_crispy_field}}
            </div>
          </div>
        </div>
        <div class="container">
        <button type="submit" class="btn btn-primary col-3 mb-2 mr-2">Update</button>
        <a href="{% url 'delete-wine' wine.pk %}" class="btn btn-danger col-3 mb-2 ml-5">Delete</a>
        <a href="{% url 'wine-home' %}" class="btn btn-info col-3 mb-2 float-right">Cancel</a>
        </div>
      </form>
    </div>
  </div>
</div>
</section>

  
{% endblock %}

wine/templates/wine/wine_list.html
{% extends 'wine/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<style>
html,
body {
  margin: 0;
  padding: 40;
  overflow-x: hidden ;
}
</style>
<div id="wine-list">
  
<section >
  <div class="container filter-section">
 <div class="col-md-12 wine-filter">
  <form method="GET" action="." name="WineFilterForm">
  <div class="form-row">
        <div class="form-group col-md-2">
      <label for="textSearch">Search by Name:</label>
      <input name="txt_srch" id="txt_srch" type="text" class="form-control-sm" placeholder="Wine">
    </div>
    <div class="form-group col-md-2">
      <label for="inputCountry">Country:</label>
      <select
            id="chooseCountry"
            class="form-control form-control-sm"
            name="country"
          >
            <option value="" disabled selected>Select Country</option>
            {% for country in country %}
            <option name="cuisine-option" value="{{ country }}"
              >{{ country }}</option
            >
            {% endfor %}
          </select>
    </div>
    <div class="form-group col-md-2">
      <label for="inputRegion">Region:</label>
      <select
            id="chooseRegion"
            class="form-control form-control-sm"
            name="region"
          >
            <option value="" disabled selected>Select Region</option>
            {% for region in region %}
            <option value="{{ region }}"
              >{{ region }}</option
            >
            {% endfor %}
          </select>
    </div>
    <div class="form-group col-md-2">
      <label for="inputRating">Rating:</label>
      <input name="vg_rating" id="inputRating" type="text" class="form-control-sm" placeholder="Minimum Rating">
    </div>
    <div class="form-group col-md-2">
      <label for="inputRetailer">Retailer:</label>
      <input name="retailer" id="inputRetailer" type="text" class="form-control-sm" placeholder="Retailer">
    </div>

    <button id="wine-filter-btn" class="btn btn-primary">Show All</button>
  </div>
  </form>
</div>
</div>
</section>

<div class="table-responsive-sm wine-list ">
    <table id="wineTable" class="table table-striped table-bordered table-sm wine-table">
      <thead class="thead-dark">
        <tr>
          <th onclick="sortTable(0)">Name</th>
          <th onclick="sortTable(1)">Country</th>
          <th onclick="sortTable(2)">Region</th>
          <th>Vintage</th>
          <th onclick="sortTable(4)" >Retailer</th>
          <th onclick="sortTable(5)">Price</th>
          <th>Comment</th>
          <th onclick="sortTable(7)">Blend</th>
          <th onclick="sortTable(8)">Rating</th>
          <th>URL</th>
          <th>Edit</th>
        </tr>
      </thead>
      <tbody>
        {% for wine in wines %}
        <tr class="wine-row">
          
          <td class="name">{{ wine.name }}</td>
          <td class="country">{{ wine.country}}</td>
          <td class="region">{{ wine.region }}</td>
          {% if wine.vintage%}
          <td>{{ wine.vintage }}</td>
          {% else %}
          <td></td>
          {% endif %}
          {% if wine.retailer%}
          <td class="retailer">{{ wine.retailer }}</td>
          {% else %}
          <td></td>
          {% endif %}
          {% if wine.price %}
          <td>£{{ wine.price }}</td>
          {% else %}
          <td></td>
          {% endif%}
          <td class="comment">{{ wine.comment }}</td>
          <td>{{ wine.blend }}</td>
          <td class="rating">{{ wine.vg_rating }}</td>
          <td>
            {% if wine.url %}
            <a href="{{ wine.url }}" target="_blank">Link</a>
            {% else %}
            {% endif %}
          </td>
          <td>
            <a href="{% url 'wine-edit' wine.pk %}">Edit</a>
          </td>
        </tr>
        {% empty %}
        <tr>
          <td colspan="12">No data.</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<!-- PAGINATION -->
<!-- <div class="pagination">
    <span class="step-links">
        {% if wines.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ wines.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ wines.number }} of {{ wines.paginator.num_pages }}.
        </span>

        {% if wines.has_next %}
            <a href="?page={{ wines.next_page_number }}">next</a>
            <a href="?page={{ wines.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
  </div> -->


 <script src="https://code.jquery.com/jquery-3.5.0.min.js" integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous">
  </script>
  <script src="{% static 'wine/js/wine_js.js' %}"></script>
 <script type="text/javascript">

</script>


  {% endblock %}

wine/templates/wine/wine_search.html
{% extends 'wine/base.html' %}

{% block content %}
<style>
  body {
    overflow: hidden;
  }
</style>

<section id="wine-search">

<div class="container menu-wrap">
<!--- Begin Wine-Searcher Code --->
<div style="width:375px;height:57px;padding:10px;margin:0 auto;background-color:#9B9B9B;vertical-align:middle;box-sizing:border-box;"> 
      <form name="searchform" method="GET" target=_blank action="https://www.wine-searcher.com/find"> 
<input type="hidden" name="Xfromsearch" value="Y"> 
          <div style="float:right;width:49px;height:37px;border-radius:0px 2px 2px 0px;box-sizing:border-box;"> 
          <button style="display:inline-block;background:none repeat scroll 0 0 #0076D6;height:37px;width:100%;padding:0;border:medium none;border-radius:0px 2px 2px 0px;box-sizing:border-box;" name="searchbutton" tabindex="3" onclick="return search_button_click();"> 
          <span style="cursor:pointer;display:block;">   
            <svg width="20px" height="20px" viewBox="0 0 40 40" version="1.1" xmlns="http://www.w3.org/2000/svg"> 
                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"> 
                    <g transform="translate(-373.000000, -2884.000000)" fill-rule="nonzero" fill="#FFF"> 
                        <g transform="translate(373.000000, 2884.000000)"> 
                            <path d="M16.8627451,33.4788235 C12.4709804,33.4987373 8.25058824,31.7707843 5.13333333,28.6764706 C2.01447059,25.5821176 0.255686431,21.3741176 0.243529529,16.9823529 C0.229742863,12.5890196 1.96533333,8.37176471 5.06431373,5.25882353 C8.1632549,2.14607843 12.3729412,0.39372549 16.7662745,0.389019608 C21.1580392,0.382901961 25.3737255,2.12309804 28.4803922,5.22823529 C31.588549,8.33180392 33.334902,12.5443137 33.3333333,16.9376471 C33.3379294,21.312549 31.6054118,25.5113725 28.5188235,28.6133333 C25.4305882,31.7138039 21.2396078,33.4631373 16.8627451,33.4784314 L16.8627451,33.4788235 Z M16.8627451,5.21607843 C13.75,5.19463529 10.7552941,6.414 8.54156863,8.60301961 C6.32784314,10.7920392 5.0765098,13.7716471 5.06270588,16.8841961 C5.04891765,19.9984706 6.27439216,22.9885098 8.46803922,25.1975294 C10.6616863,27.4064706 13.6441176,28.6518824 16.7586275,28.658 C19.8713725,28.6656588 22.8601961,27.4340392 25.0629412,25.2342745 C27.2672941,23.0360392 28.506549,20.0503529 28.506549,16.9378039 C28.5126784,13.8403922 27.2917647,10.8656471 25.1088627,8.66878431 C22.9259608,6.47054902 19.9602353,5.22976471 16.8629804,5.21596078 L16.8627451,5.21607843 Z" id="Fill-1"> </path> 
                            <polygon points="36.1996078 39.6078431 25.78 29.2509804 29.1929804 25.8349412 39.6082745 36.1918039"> </polygon> 
                        </g> 
                    </g> 
                </g> 
            </svg>   
          </span> 
       </button> 
      </div> 
      <div style="text-align:left;width:355px;border-radius:2px 0px 0px 2px;box-sizing:border-box;"> 
        <div style="float:right;width:75px;box-sizing:border-box;"> 
          <input style="font-size:14px;font-family:Verdana;height:37px;width:100%;background:#fff;padding-left:10px;padding-right:10px;margin:0;outline:0 none;box-sizing:border-box;border:0 none" type="text" size="4" maxlength="4" id="Xvintage" name="Xvintage" value="" tabindex="2" title="Vintage (use 'NV' for non-vintage). Leave blank to search all vintages." placeholder="Vintage"> 
        </div> 
        <div style="text-align:left;width:231px;overflow:visible;margin:0;background:#fff;border-radius:2px 0px 0px 2px;position:relative;box-sizing:border-box;"> 
          <input style="font-size:14px;font-family:Verdana;height:37px;border-radius:2px 0px 0px 2px;border:0 none;outline:none;padding-left:45px;padding-right:10px;vertical-align:top;width:99%;text-overflow:ellipsis;background:#fff;background-image:url('/images/logo_splash.png');background-repeat:no-repeat;background-size:25px 14px;background-position:10px;position:relative;box-sizing:border-box;" type="text" maxlength="100" name="Xwinename" id="Xwinename" value="" tabindex="1" title="Search phrase"  placeholder="Type any wine name"  autocomplete="off" spellcheck="false" dir="auto" > 
          <div style="border-right:1px solid #999;height:25px;width:1px;position:absolute;right:-0.5px;top:5px"> </div> 
        </div>                 
      </div>  
    </form>            
  </div>
<!--- End Wine-Searcher Code --->

</div>
</section>
{% endblock %}